### ISSUE TITLE
snap config does not work

### ISSUE THREAD

**Issue by tg123** [tg123/sshpiper#190]
@tg123 also, `snap set` will fail

_Originally posted by @yujincheng08 in https://github.com/tg123/sshpiper/issues/165#issuecomment-1675612947_

**Comment by tg123** [comment]
fixed in release 1.2.2

**Comment by yujincheng08** [comment]
@tg123 no. it's still not using the correct configuration. Please reopen it.

**Comment by tg123** [comment]
sorry 
changed to snap set sshpiperd.port=1234

**Comment by yujincheng08** [comment]
I see. But I need to reconfigure all settings...

**Comment by tg123** [comment]
> I see. But I need to reconfigure all settings...

sorry, i am with you
but the parameters changed a log from v0 to v1, have to put a namespace for parameters
